export * from './create-diagnostic.input';
export * from './create-medical-history.input';
export * from './create-pet.input';
export * from './create-surgical-intervention.input';
export * from './create-treatment.input';
export * from './update-medical-history.input';
export * from './update-pet.input';
export * from './update-surgical-intervention.input';
export * from './update-treatment.input';
