export * from './create-clinical-sheet.input';
export * from './create-health-certificate.input';
export * from './create-euthanasia.input';
export * from './create-consent-surgery.input';
export * from './create-vaccines.input';
export * from './create-vaccine-clinical-sheet.input';
export * from './create-deworming.input';
export * from './create-heat.input';
export * from './create-bill.input';
